/**
 * Build script for blobboxes browser bundle.
 *
 * Produces two variants:
 *   dist/blobboxes.bundle.js      — full bundle with roaring-wasm (Phase 3)
 *   dist/blobboxes.lite.js        — snapshot + observer only, no WASM deps (Phase 1-2)
 *
 * The lite bundle is a self-contained IIFE that can be injected as a string
 * into any browser context (CDP isolated world, Qt ApplicationWorld, etc.)
 * without needing npm, fetch, or any external resources.
 *
 * Usage:
 *   node build.js              # build both variants
 *   node build.js --no-roaring # build lite variant only
 */

const esbuild = require('esbuild');
const fs = require('fs');
const path = require('path');

const noRoaring = process.argv.includes('--no-roaring');

async function build() {
    // Phase 1-2: lite bundle (no roaring-wasm dependency)
    await esbuild.build({
        entryPoints: [path.join(__dirname, 'src/index.js')],
        bundle: true,
        format: 'iife',
        // No globalName — index.js sets globalThis.blobboxes directly
        outfile: path.join(__dirname, 'dist/blobboxes.lite.js'),
        minify: false, // keep readable for debugging
        target: ['es2020'],
        // Stub out roaring-wasm — loadFilters() will throw a clear error
        external: ['roaring-wasm'],
        define: {},
        banner: {
            js: '// blobboxes browser bundle (lite) — snapshot + observer, no WASM\n// Generated by build.js — do not edit\n',
        },
    });

    const liteSize = fs.statSync(path.join(__dirname, 'dist/blobboxes.lite.js')).size;
    console.log(`dist/blobboxes.lite.js: ${(liteSize / 1024).toFixed(1)} KB`);

    if (!noRoaring) {
        // Phase 3: full bundle with roaring-wasm inlined
        // roaring-wasm's browser entry (browser/index.mjs) has the WASM
        // binary pre-inlined as base64, so it is fully self-contained.
        // We use esbuild's "browser" condition to pick up that entry point.
        try {
            await esbuild.build({
                entryPoints: [path.join(__dirname, 'src/index.js')],
                bundle: true,
                format: 'iife',
                // No globalName — index.js sets globalThis.blobboxes directly
                outfile: path.join(__dirname, 'dist/blobboxes.bundle.js'),
                minify: false,
                target: ['es2020'],
                // Tell esbuild to use the "browser" export condition
                // so it picks roaring-wasm/browser/index.mjs (base64 WASM inlined)
                conditions: ['browser'],
                // The browser entry uses top-level await for WASM init internally;
                // we handle async init in loadFilters()
                supported: { 'top-level-await': true },
                banner: {
                    js: '// blobboxes browser bundle (full) — snapshot + observer + roaring-wasm\n// Generated by build.js — do not edit\n',
                },
            });

            const fullSize = fs.statSync(path.join(__dirname, 'dist/blobboxes.bundle.js')).size;
            console.log(`dist/blobboxes.bundle.js: ${(fullSize / 1024).toFixed(1)} KB`);
        } catch (e) {
            console.warn('Full bundle build failed:', e.message);
            console.warn('Run `npm install` to install dependencies, then rebuild.');
        }
    }
}

build().catch(e => {
    console.error(e);
    process.exit(1);
});
